spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/nagarro

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web

springdoc:
  api-docs:
    path: /v1/accounts/v3/api-docs
  swagger-ui:
    path: /v1/accounts/swagger-ui/index.html

grpc:
  server:
    port: 9090
    interceptors:
      - net.devh.boot.grpc.server.tracing.TracingServerInterceptor
  client:
    customer-grpc-service:
      address: 'discovery:///CUSTOMER-MANAGEMENT-SERVICE'
      negotiation-type: plaintext
      lazy-initialization: true
      interceptors:
        - net.devh.boot.grpc.client.tracing.TracingClientInterceptor

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    home-page-url-path: ${server.servlet.context-path}
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    metadata-map:
      grpc.port: "9090"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    propagation:
      type: W3C
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
