spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/nagarro

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web

grpc:
  server:
    port: 9091
    interceptors:
      - net.devh.boot.grpc.server.tracing.TracingServerInterceptor
  client:
    account-grpc-service:
      address: 'discovery:///ACCOUNT-MANAGEMENT-SERVICE'
      negotiation-type: plaintext
      lazy-initialization: true
      interceptors:
        - net.devh.boot.grpc.client.tracing.TracingClientInterceptor

eureka:
  instance:
    home-page-url-path: ${server.servlet.context-path}
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info
