spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-management-service
              uri: lb://ACCOUNT-MANAGEMENT-SERVICE
              predicates:
                - Path=/v1/accounts/**

            - id: account-grpc-route
              uri: lb://ACCOUNT-MANAGEMENT-SERVICE
              predicates:
                - Path=/com.nagarro.bank.account.grpc.AccountGrpcService/**
              metadata:
                option: h2c

            - id: customer-management-service
              uri: lb://CUSTOMER-MANAGEMENT-SERVICE
              predicates:
                - Path=/v1/customers/**

            - id: customer-grpc-route
              uri: lb://CUSTOMER-MANAGEMENT-SERVICE
              predicates:
                - Path=/com.nagarro.bank.customer.grpc.CustomerGrpcService/**
              metadata:
                option: h2c
  reactor:
    context-propagation: auto
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  netty:
    connection-timeout: 2s
    http2:
      enabled: true


management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    propagation:
      type: W3C
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: refresh, gateway, health, info
    gateway:
      enabled: true
      access: unrestricted
  observations:
    http:
      server:
        requests:
          name: http.server.requests
    enable:
      jdbc: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %5p traceId:%X{traceId:-} spanId:%X{spanId:-} correlationId:%X{X-Correlation-ID:-} %logger{36} - %msg%n"
